services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: >
          sh -c "until nc -z db 5432; do echo 'Waiting for db...'; sleep 1; done &&
                uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env 
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: user_db

  redis:
    image: redis
    ports:
      - 6379:6379
